# Theme settings
remote_theme: pages-themes/primer
plugins:
  - jekyll-remote-theme

# Site settings
title: Motive Archive Emails
description: Drafts of marketing emails for Motive Archive
# Other settings can be added here
