# Theme settings
remote_theme: pages-themes/primer
plugins:
  - jekyll-remote-theme

# Site settings
title: Your Site Title
description: A brief description of your site
# Other settings can be added here
